# Generated by Django 4.2.2 on 2023-07-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Key name'),
        ),
    ]
