# Generated by Django 4.2.2 on 2023-07-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_page_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='key',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Key name'),
        ),
    ]
